import numpy as np
from clustering import KMclustering

########################
# Author: Jernej Vivod #
########################

# Second Home Assignment for the Introduction to Data Analysis Class
# See instructions in folder.

# Load dictionary stored in results_dict.npy that was generated by the text_analyzer script.
results_dict = np.load('results_dict.npy').item()

# Create new instance of KMclustering class implementing methods used for permorming the
# k-medoids clustering algorithm. Initialize with results_dict data.
km = KMclustering(results_dict)

# Run with 5 medoids.
km.run(5)